### ISSUE TITLE
Llevar registro de meetings y toda la info necesaria dentro de la wiki de Github

### ISSUE THREAD

**Issue by TamiSorsaburu** [TamiSorsaburu/Proyecto-Colaborativo#5]
(Ver consideraciones generales)

**Comment by maru221** [comment]
Aquí llevaremos un registro de la reuniones que tenemos en el grupo.
Nuestra primera Reunión fue el  día lunes 12 de septiembre donde expusimos las diferentes ideas para crear nuestro proyecto.
decidimos analizar cada propuesta y decidir en la próxima reunión que proyecto realizaremos.
